version: '3.7'

services:
  mongo:
    container_name: mongo
    image: mongo:4
    ports:
      - "27017:27017"
    volumes:
      - type: volume
        source: mongo
        target: /data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: yapi
    restart: always
    volumes:
      - type: bind
        source: ./init-mongo.js
        target: /docker-entrypoint-initdb.d/init-mongo.js
        read_only: true
      - type: volume
        source: mongo
        target: /data/db
    networks:
      - yapi

  yapi:
    depends_on:
      - mongo
    build:
      context: ./
    container_name: yapi
    image: yapi
    command: "yapi server"              #第一次启动使用
    #command: "node /yapi/vendors/server/app.js"             #后面启动使用
    ports: 
      - "9090:9090"
      - "3000:3000"
    restart: always
    volumes:
      - type: volume
        source: yapi
        target: /yapi
    networks:
      - yapi
      
volumes:
  mongo:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /data/yapi/mongo
  yapi:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /data/yapi/yapi

networks:
  yapi:
    driver: bridge
